---
apiVersion: k3d.io/v1alpha2
kind: Simple
name: foo
servers: 1
agents: 1
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraServerArgs:
      - --disable=servicelb
      - --disable=traefik
      - --flannel-backend=none
      - --disable-network-policy
